var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                         x                                                      ",
   "                                                                                ",
   "                                                                                ",
   "                         w      x  ooooo                           !            ",
   "                         x         xxxxx                          xvx           ",
   "                               x E             x                                ",
   "                                xxx       xo                                    ",
   "                                  xx       x!                                   ",
   "  x                                xxx      xxx                          o      ",
   "  x             s    o                x        !                  ooo  ! x ! o  ",
   "  x  @  x!!!!x  x                        x     !               x!xxxxx x   x x  ",
   "   xxxxx xxxx xx x   !          o           x  !              x                 ",
   "                 x   x   xx             x      !             x                  ",
   "                  x     x  x       E x         !!!xxx      Ex                   ",
   "                   xxxxx    xxx!!!xxx xx xxx         x!!!!!x                    ",
   "                               xxx                    xxxxx                     ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x x",
   "                                       vv                          v    v                                     x   ",
   "                                                                                                              x |w",
   "                                                                                                              x   ",
   "                                                                                                              x   ",
   "                                                                                                              x | ",
   "                                                                                                              x   ",
   "                                                   x x  x  x     x   x   x          s        o    o    o      x   ",
   "                                                 xx     =    xx  | = | = |  xx     xx     xxxxxxxxxxxxxxxxxxxxx   ",
   "                                              x                                    xx                           | ",
   "                                              x                                    xx                             ",
   "                                                xxx                x   x           xx                             ",
   "                                  v                 x                              xxx                            ",
   "                                                     x                             xxe                            ",
   "                                                     vx                            xx                |   |      | ",
   "                                                                                   xx                             ",
   "         !       o o                                     xxx   x  x                xx                  o   o x o  ",
   "    x x  v     xxxxxxx    x   xxx   xxx        x     x               x   x   x     xx        xxxxxxxxxxxxxxxx|xxxx",
   "    v v                  x                         x        s      x               xx                            x",
   "             x     =    x         o       x x x   x e  xx x x x x x          w     xx       e                   wx",
   "     @   x  xx   x  x  x        x x x  xxx     x    xxx              x   x   x     xxxx     xxxxxxxxxxxxxxxxxxxxxx",
   "    xxx                                                                            xx                      E      ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        !!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        !!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!      xx!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         o o o       o o o  x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        o o o o     o o o o x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         o o o       o o o  x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                        o    o                                                                                ",
   "                        x    x                                                                                ",
   "                        |x       xx                                                                           ",
   "                         |x            xxx =  =  =xx            =x                                            ",
   "                          |x                            xxxx                                                  ",
   "                           |x                               x                                                 ",
   "                            |                                x  xxxxxxxxxxxx                                  ",
   "                                                              x     =       x                                 ",
   "                                                                                                              ",
   "                                                                                 xx                           ",
   "                                           o o o o     o oeo o       o          x                             ",
   "                               x  x   x   xxxxxxxxx   xxxxxxxxx    xxxxx    x xx                              ",
   "                              x       e                                                                       ",
   "                             x                                                                                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                       x                                                                                      ",
   "                        x      e                                                                              ",
   "                         x                                                                                    ",
   "                          x                                                                                   ",
   "                           x                                                                                  ",
   "                            x  o oeo o o              x!!!!!!!!!!!!!!x                                        ",
   "              x              xxxxxxxxxxxxx x            v    v    v                                           ",
   "              |             x         v      x                                                                ",
   "             x                                                                                                ",
   "             |                                  x                                                             ",
   "            x                                                                                                 ",
   "            |                                      x                                                          ",
   "           x                  x          =x                                                                   ",
   "           |              x   x           =x          x    x   x    x    x  x                                 ",
   "                         xxxx x           x                              |       x                            ",
   "                        xxx   x           =x                                    xxo                           ",
   "                       xxxx   x          =x                                    xxxx                           ",
   "                      xxxxx xxx                                               xxxx                            ",
   "                     xxxxxx  ox                                              xxxxxo                           ",
   "  x      @          xxxxxxx  oxx          xe x    x!!!!x s  x    x    xx o xxxxxxxx              xo o o o ox  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
